services:
  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: plansmartai
      POSTGRES_PASSWORD: plansmartai
      POSTGRES_DB: plansmartai
    volumes:
      - postgres_storage:/var/lib/postgresql/data

volumes:
  qdrant_storage:
  postgres_storage:
